[options]
Architecture = auto
Color
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# blunux2 custom repository
[blunux2]
SigLevel = Optional TrustAll
Server = file:///run/media/crux/ss4/test/blunux2SB/aurrepo/x86_64
