use blunux_config::BlunuxConfig;

use crate::packages;

// ---------------------------------------------------------------------------
// settings.conf — Calamares module pipeline
// ---------------------------------------------------------------------------

pub fn settings_conf(config: &BlunuxConfig) -> String {
    let mut exec_modules = vec![
        "partition",
        "mount",
        "unpackfs",
        "machineid",
        "fstab",
        "locale",
        "keyboard",
        "localecfg",
    ];

    if config.install.encryption {
        exec_modules.push("luksbootkeyfile");
    }

    exec_modules.extend([
        "users",
        "displaymanager",
        "networkcfg",
        "hwclock",
        "services-systemd",
        "shellprocess",
    ]);

    // Bootloader module: grub and systemd-boot use the standard module.
    // nmbl (EFISTUB) is handled entirely via shellprocess — no bootloader module.
    match config.install.bootloader.as_str() {
        "grub" => {
            exec_modules.push("grubcfg");
            exec_modules.push("bootloader");
        }
        "systemd-boot" => {
            exec_modules.push("bootloader");
        }
        "nmbl" => {
            // EFISTUB: handled in shellprocess, no bootloader module needed
        }
        _ => {
            exec_modules.push("bootloader");
        }
    }

    exec_modules.push("umount");

    let exec_list = exec_modules
        .iter()
        .map(|m| format!("    - {}", m))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# Auto-generated by blunux-toml2cal from config.toml
# Do not edit — modify config.toml and re-run the translator.

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary

  - exec:
{exec_list}

  - show:
    - finished
"#
    )
}

// ---------------------------------------------------------------------------
// locale.conf
// ---------------------------------------------------------------------------

pub fn locale_conf(config: &BlunuxConfig) -> String {
    let lang = config
        .locale
        .language
        .first()
        .map(|s| s.as_str())
        .unwrap_or("en_US");

    // Split timezone into region/zone (e.g. "Europe/Stockholm" → "Europe", "Stockholm")
    let (region, zone) = config
        .locale
        .timezone
        .split_once('/')
        .unwrap_or(("UTC", "UTC"));

    format!(
        r#"# Auto-generated by blunux-toml2cal
localeGenPath: /etc/locale.gen

GS_insert: UTF-8

region: "{region}"
zone: "{zone}"

# Primary locale
LANG: "{lang}.UTF-8"
LC_NUMERIC: "{lang}.UTF-8"
LC_TIME: "{lang}.UTF-8"
LC_MONETARY: "{lang}.UTF-8"
LC_PAPER: "{lang}.UTF-8"
LC_NAME: "{lang}.UTF-8"
LC_ADDRESS: "{lang}.UTF-8"
LC_TELEPHONE: "{lang}.UTF-8"
LC_MEASUREMENT: "{lang}.UTF-8"
LC_IDENTIFICATION: "{lang}.UTF-8"
"#
    )
}

// ---------------------------------------------------------------------------
// keyboard.conf
// ---------------------------------------------------------------------------

pub fn keyboard_conf(config: &BlunuxConfig) -> String {
    let layout = config
        .locale
        .keyboard
        .first()
        .map(|s| s.as_str())
        .unwrap_or("us");

    format!(
        r#"# Auto-generated by blunux-toml2cal
model: "pc105"
layout: "{layout}"
variant: ""
"#
    )
}

// ---------------------------------------------------------------------------
// partition.conf
// ---------------------------------------------------------------------------

pub fn partition_conf(config: &BlunuxConfig) -> String {
    let encryption_block = if config.install.encryption {
        r#"
luksGeneration: luks2
"#
    } else {
        ""
    };

    // Map config.toml swap value to Calamares swap choice list
    let swap_line = match config.disk.swap.as_str() {
        "none" => "  - none",
        "small" => "  - small",
        "suspend" => "  - suspend",
        "file" => "  - file",
        _ => "  - small",
    };

    format!(
        r#"# Auto-generated by blunux-toml2cal
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

defaultFileSystemType: ext4
{encryption_block}

swapChoices:
{swap_line}
"#
    )
}

// ---------------------------------------------------------------------------
// users.conf
// ---------------------------------------------------------------------------

pub fn users_conf(config: &BlunuxConfig) -> String {
    let autologin = if config.install.autologin {
        "true"
    } else {
        "false"
    };

    format!(
        r#"# Auto-generated by blunux-toml2cal
defaultGroups:
  - name: wheel
    must_exist: false
    system: true
  - video
  - audio
  - storage
  - optical
  - network
  - lp
  - scanner

autologinGroup: autologin
doAutologin: {autologin}
sudoersGroup: wheel
setRootPassword: true

user:
  shell: /bin/bash
  name: "{username}"
  hostname: "{hostname}"
"#,
        username = config.install.username,
        hostname = config.install.hostname,
    )
}

// ---------------------------------------------------------------------------
// bootloader.conf
// ---------------------------------------------------------------------------

pub fn bootloader_conf(config: &BlunuxConfig) -> String {
    match config.install.bootloader.as_str() {
        "grub" => {
            r#"# Auto-generated by blunux-toml2cal
efiBootLoader: "grub"
grubInstall: "default"
grubProbe: true
installEFIFallback: true
"#
            .to_string()
        }
        "systemd-boot" => {
            r#"# Auto-generated by blunux-toml2cal
efiBootLoader: "systemd-boot"
installEFIFallback: false
"#
            .to_string()
        }
        "nmbl" => {
            // EFISTUB: Calamares bootloader module is skipped entirely.
            // Installation is handled via shellprocess calling efibootmgr.
            r#"# Auto-generated by blunux-toml2cal
# Bootloader: nmbl (EFISTUB direct boot)
# The bootloader Calamares module is NOT used.
# EFISTUB entry is created via shellprocess using efibootmgr.
efiBootLoader: "systemd-boot"
"#
            .to_string()
        }
        _ => {
            format!(
                "# Auto-generated by blunux-toml2cal\n# Unknown bootloader: {}\nefiBootLoader: \"grub\"\n",
                config.install.bootloader
            )
        }
    }
}

// ---------------------------------------------------------------------------
// unpackfs.conf
// ---------------------------------------------------------------------------

pub fn unpackfs_conf() -> String {
    r#"# Auto-generated by blunux-toml2cal
unpack:
  - source: /run/miso/bootmnt/arch/x86_64/airootfs.sfs
    sourcefs: squashfs
    destination: ""
"#
    .to_string()
}

// ---------------------------------------------------------------------------
// shellprocess.conf — post-install commands
// ---------------------------------------------------------------------------

pub fn shellprocess_conf(config: &BlunuxConfig) -> String {
    let mut scripts = Vec::new();

    // Remove live-session packages
    scripts.push(
        r#"  - command: "chroot $ROOT pacman -Rns --noconfirm mkinitcpio-archiso""#.to_string(),
    );

    // Install non-default kernel if needed
    if config.kernel.kernel_type != "linux" {
        scripts.push(format!(
            r#"  - command: "chroot $ROOT pacman -S --noconfirm {} {}-headers""#,
            config.kernel.kernel_type, config.kernel.kernel_type
        ));
    }

    // Regenerate initramfs
    scripts.push(r#"  - command: "chroot $ROOT mkinitcpio -P""#.to_string());

    // EFISTUB: create EFI boot entry via efibootmgr
    if config.install.bootloader == "nmbl" {
        scripts.push(
            r#"  - command: >
      chroot $ROOT efibootmgr --create
      --disk /dev/$(lsblk -no PKNAME $(findmnt -n -o SOURCE $ROOT/boot/efi))
      --part 1
      --label "blunux2"
      --loader /vmlinuz-linux
      --unicode "root=PARTUUID=$(blkid -s PARTUUID -o value $(findmnt -n -o SOURCE $ROOT)) rw rootflags=subvol=@ quiet splash initrd=\\initramfs-linux.img""#
                .to_string(),
        );
    }

    // Install user-selected packages
    let pkgs = packages::resolve(config);
    if !pkgs.is_empty() {
        scripts.push(format!(
            r#"  - command: "chroot $ROOT pacman -S --noconfirm --needed {}""#,
            pkgs.join(" ")
        ));
    }

    // Input method setup
    if config.input_method.enabled {
        let im_pkgs = match config.input_method.engine.as_str() {
            "kime" => "kime kime-indicator",
            "fcitx5" => "fcitx5 fcitx5-hangul fcitx5-gtk fcitx5-qt fcitx5-configtool",
            "ibus" => "ibus ibus-hangul",
            _ => "",
        };
        if !im_pkgs.is_empty() {
            scripts.push(format!(
                r#"  - command: "chroot $ROOT pacman -S --noconfirm --needed {im_pkgs}""#
            ));
        }

        let env_vars = match config.input_method.engine.as_str() {
            "kime" => "GTK_IM_MODULE=kime\\nQT_IM_MODULE=kime\\nXMODIFIERS=@im=kime",
            "fcitx5" => "GTK_IM_MODULE=fcitx\\nQT_IM_MODULE=fcitx\\nXMODIFIERS=@im=fcitx",
            "ibus" => "GTK_IM_MODULE=ibus\\nQT_IM_MODULE=ibus\\nXMODIFIERS=@im=ibus",
            _ => "",
        };
        if !env_vars.is_empty() {
            scripts.push(format!(
                r#"  - command: "echo -e '{env_vars}' > $ROOT/etc/environment.d/input-method.conf""#
            ));
        }
    }

    // Copy live session theme to installed system
    scripts
        .push(r#"  - command: "cp -r /home/liveuser/.config/plasma* $ROOT/etc/skel/.config/ 2>/dev/null || true""#.to_string());

    // Clean pacman cache
    scripts.push(r#"  - command: "chroot $ROOT pacman -Scc --noconfirm""#.to_string());

    // Set kernel parameters
    if config.install.bootloader == "grub" {
        scripts.push(
            r#"  - command: >
      sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
      $ROOT/etc/default/grub"#
                .to_string(),
        );
    }

    let script_block = scripts.join("\n\n");

    format!(
        r#"# Auto-generated by blunux-toml2cal from config.toml

script:
{script_block}
"#
    )
}

// ---------------------------------------------------------------------------
// services-systemd.conf
// ---------------------------------------------------------------------------

pub fn services_systemd_conf(config: &BlunuxConfig) -> String {
    let mut services = vec!["NetworkManager"];

    if config.packages.desktop.kde {
        services.push("sddm");
    }

    if config.packages.utility.bluetooth {
        services.push("bluetooth");
    }

    if config.packages.virtualization.docker {
        services.push("docker");
    }

    let svc_list = services
        .iter()
        .map(|s| format!("  - name: {}\n    mandatory: false", s))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"# Auto-generated by blunux-toml2cal

services:
{svc_list}
"#
    )
}

// ---------------------------------------------------------------------------
// displaymanager.conf
// ---------------------------------------------------------------------------

pub fn displaymanager_conf(config: &BlunuxConfig) -> String {
    let dm = if config.packages.desktop.kde {
        "sddm"
    } else {
        "lightdm"
    };

    let autologin = if config.install.autologin {
        format!(
            "defaultDesktopEnvironment:\n  executable: \"startplasma-wayland\"\n  desktopFile: \"plasma\"\n"
        )
    } else {
        String::new()
    };

    format!(
        r#"# Auto-generated by blunux-toml2cal
displaymanagers:
  - {dm}

{autologin}"#
    )
}
